[package]
name = "power-menu"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
shellexpand = "3.1.1"
sysinfo = "0.36.1"
toml = "0.9.8"
