[package]
name = "sidebar"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
glib = "0.21.5"
gtk4 = { version = "0.10.3", features = ["v4_10"] }
gtk4-layer-shell = "0.7.1"
serde_json = "1.0.149"
