[package]
name = "clip-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dirs = "6.0.0"
serde = { version = "1.0.228", features = ["derive"] }
sysinfo = "0.36.1"
toml = "0.9.8"
