[package]
name = "cloudflare-toggle"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
serde_json = "1.0"
toml = "0.9.8"
serde = { version = "1.0.228", features = ["derive"] }
dirs = "6.0.0"
